# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e39adf75edbec4781a664a80f15e1b08eadc4158de0aadac1b4738ad0f7de71d2b3df274202e7ae4ce277130c3772523392d66e5bce3254cb03795f34bc4884

test:
  secret_key_base: 760222fc6e5089a0c22d86d2e4d499eabd9bebeaba6c2bb9c747cb29e518c335f649976e3cf38fd402a1083de6a6daec5988b7c69bf19396e4a04a4394101f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
